spring:
  boot:
    p1: lyh

hero:
  name: dev_李四${random.uuid}
  age: 9999
  height: 70
  go: 'local_liyaohui'

animal:
  desc: 动物2
  email: lyzx_123_hero@163.com
  list:
  - dog2
  - cat2
  - pig2

debug: false